// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2QRdQx1wUFkOnTs9LJWDhdmoDASFzpI',
    appId: '1:766734722649:web:f2fa832150f1f9938f3348',
    messagingSenderId: '766734722649',
    projectId: 'unfurl-f6582',
    authDomain: 'unfurl-f6582.firebaseapp.com',
    storageBucket: 'unfurl-f6582.firebasestorage.app',
    measurementId: 'G-NS0VX42DKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_Pq5KsGxZEW-c4iFWJq4ebT2prAeJlU',
    appId: '1:766734722649:android:34249db53ad09e9b8f3348',
    messagingSenderId: '766734722649',
    projectId: 'unfurl-f6582',
    storageBucket: 'unfurl-f6582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhESGuMd6-VwRLFFx3F2yE8ivwTZEE6iw',
    appId: '1:766734722649:ios:42262de4f091d6fe8f3348',
    messagingSenderId: '766734722649',
    projectId: 'unfurl-f6582',
    storageBucket: 'unfurl-f6582.firebasestorage.app',
    androidClientId: '766734722649-t2ohljb039l1i9ln4muu84kpi0qo116l.apps.googleusercontent.com',
    iosClientId: '766734722649-4c744m6bfu1fb65mbs049deogmndr9eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.unfurl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhESGuMd6-VwRLFFx3F2yE8ivwTZEE6iw',
    appId: '1:766734722649:ios:42262de4f091d6fe8f3348',
    messagingSenderId: '766734722649',
    projectId: 'unfurl-f6582',
    storageBucket: 'unfurl-f6582.firebasestorage.app',
    androidClientId: '766734722649-t2ohljb039l1i9ln4muu84kpi0qo116l.apps.googleusercontent.com',
    iosClientId: '766734722649-4c744m6bfu1fb65mbs049deogmndr9eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.unfurl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm2QRdQx1wUFkOnTs9LJWDhdmoDASFzpI',
    appId: '1:766734722649:web:19c6fbff01c22f868f3348',
    messagingSenderId: '766734722649',
    projectId: 'unfurl-f6582',
    authDomain: 'unfurl-f6582.firebaseapp.com',
    storageBucket: 'unfurl-f6582.firebasestorage.app',
    measurementId: 'G-BMT61P0EM2',
  );
}
